name: release
on: [push]
jobs:
 # build:
 #   runs-on: ubuntu-latest
 #   steps:
 #     - uses: actions/checkout@v2.1.0
 #     - uses: actions/cache@v1.1.2
 #       with:
 #         path: Library
 #         key: Library
 #     - uses: webbertakken/unity-builder@v0.12
 #       env:
 #         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
 #         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
 #         UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
 #       with:
 #         unityVersion: 2019.3.7f1
 #     - uses: actions/upload-artifact@v1
 #       with:
 #         name: build
 #         path: build
  create_installer:
#    needs: [build]
    runs-on: windows-latest
    outputs:
      version:  ${{ steps.getVersion.outputs.out }}
    steps:
      - uses: actions/checkout@v2.1.0
      - id: getVersion
        run: echo "::set-output name=out::$(git tag | tail -1)"
#      - uses: actions/download-artifact@v1
#        with:
#          name: build
#      - run: .\InnoSetup\ISCC.exe .\InnoSetup\installer.iss "/DMyAppVersion=${{ steps.getVersion.outputs.out }}"
      - run: echo "${{ getVersion.outputs.version }}"
#      - uses: actions/upload-artifact@v1
#       with:
#        name: installer
#          path: installer
