name: release
on: 
  release:
    types: published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/*
  create_installer:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - shell: bash
        run: sh build.sh
        working-directory: InnoSetup
      - shell: cmd
        run:  ISCC.exe "/DMyAppName=Познавательная Реальность" installer.iss
        working-directory: InnoSetup
      - shell: bash
        run: rm installer.iss   
      - uses: actions/upload-artifact@v2
        with:
          name: installer
          path: installer/*
  upload_assets:
    needs: [create_installer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/download-artifact@v1
        with:
          name: build
      - uses: actions/download-artifact@v1
        with:
          name: installer 
      - uses: meeDamian/github-release@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            build/*
            installer/*
          gzip: folders
          allow_override: true
