name: release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: webbertakken/unity-builder@v0.12
        with:
          unityVersion: 2019.3.7f1
  create_installer:
    needs: [build]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - run: .\InnoSetup\ISCC.exe .\InnoSetup\installer.iss
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: installer
        path: installer
