name: release
on: 
  release:
    types: published
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: webbertakken/unity-builder@v0.12
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: 2019.3.7f1
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  create_installer:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/download-artifact@v1
        with:
          name: build
      - shell: bash
        id: getVersion
        run: sh getVersion.sh
        working-directory: InnoSetup
      - shell: cmd
        run:  ISCC.exe "/DMyAppName=Познавательная Реальность" installer.iss
        working-directory: InnoSetup     
      - uses: actions/upload-artifact@v2
        with:
          name: installer
          path: installer
  upload_assets:
    needs: [create_installer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/download-artifact@v1
        with:
          name: build
      - uses: actions/download-artifact@v1
        with:
          name: installer 
      - uses: meeDamian/github-release@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            build/StandaloneWindows64/
            installer/
          allow_override: true
          


