name: release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: webbertakken/unity-builder@v0.12
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: 2019.3.7f1
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
  create_installer:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/download-artifact@v1
        with:
          name: build     
      - shell: bash
        run: |
          cd InnoSetup
          sh getVersion.sh
      - run: |
          cd InnoSetup
          ISCC.exe installer.iss
      - uses: actions/upload-artifact@v1
        with:
          name: installer
          path: installer
