name: Action
on: [push]
jobs:
  chache:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
          key: Library
    - name: Unity - Builder
      uses: webbertakken/unity-builder@v0.12
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        unityVersion: 2019.3.7f1
        targetPlatform: StandaloneWindows64
    - name: Generate new cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v1.1.2
      with:
          key: Library
