name: Action
on: [push]
env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
jobs:
  Tests_and_build:
    runs-on: [ubuntu-latest]
    matrix:
      testMode:
        - playmode
        - editmode
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: Library
        key: Library
    - uses: webbertakken/unity-test-runner@v1.6
      id: tests
      with:
        unityVersion: 2019.3.7f1
        testMode: playmode
    - uses: actions/upload-artifact@v1
      with:
        name: test results
        path: ${{ steps.tests.outputs.artifactsPath }}
    - name: Unity - Builder
      uses: webbertakken/unity-builder@v0.12
      with:
        unityVersion: 2019.3.7f1
        targetPlatform: StandaloneWindows64
    - name: Generate new cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v1.1.2
      with:
        path: Library
        key: Library
