name: Action
on: [push]
env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
jobs:
  UnitTests:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        testMode:
          - playmode
          - editmode
        UnityVersion:
          - 2019.3.7f1
    steps:
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: Library
        key: Library
    - run: ls -l
    - uses: actions/checkout@v2.1.0
      with:
        clean: false
        lfs: true
    - uses: webbertakken/unity-test-runner@v1.6
      id: tests
      with:
        unityVersion: ${{ matrix.UnityVersion }}
        testMode: ${{ matrix.testMode }}
        artifactsPath: ${{ matrix.testMode }}-artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: Test results for ${{ matrix.testMode }}
        path: ${{ steps.tests.outputs.artifactsPath }}
    - name: Generate new cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v1.1.2
      with:
        path: Library
        key: Library
  Build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        UnityVersion: 
          - 2019.3.7f1
    steps:
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: Library
        key: Library
    - uses: actions/checkout@v2.1.0
      with:
        clean: false
        lfs: true
    - name: Unity - Builder
      uses: webbertakken/unity-builder@v0.12
      with:
        unityVersion: ${{ matrix.UnityVersion }}
        targetPlatform: StandaloneWindows64
