name: Action
on: [push]
jobs:
  chache:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
          path: Library
          key: Library
    - name: Unity - Builder
      uses: webbertakken/unity-builder@v0.12
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        unityVersion: 2019.3.7f1
        targetPlatform: StandaloneWindows64


      
